# Please adjust to your needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - name: seting up github local repo for changes
  - init: git branch -a
    command: git checkout gitpod

  - name: installing nodejs dependencies
  - before: npx playwright install-deps
  - init: npm install
    command: npm run dev
