name: validate code change

on: [push, pull_request]

env: 
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Print env
        run: echo $DATABASE_URL
